
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <signal.h>
#include <unistd.h>
#include <sys/stat.h>
#include <stdint.h>
#include <tt_sdk/sdk.h>
#include <zephyr/fs/fs.h>

#define BUFFER_SIZE 8192

static char* enrollmentCaCert = NULL;
static char* enrollmentClientCert = NULL;
static char* enrollmentPrivKey = NULL;
static TtEnrollmentData enrollmentData;

static char* readFile(const char* filename) {
    FILE* file = fopen(filename, "rb");
    if (!file) {
        fprintf(stderr, "Could not open '%s'\n", filename);
        return NULL;
    }
    fseek(file, 0, SEEK_END);
    long size = ftell(file);
    rewind(file);
    char* buffer = malloc(size + 1);
    if (!buffer) {
        fclose(file);
        return NULL;
    }
    fread(buffer, 1, size, file);
    buffer[size] = ' ';
    fclose(file);
    return buffer;
}

static const TtEnrollmentData* loadEnrollmentData(const char* folder, const char* server) {
    char path[BUFFER_SIZE];

    snprintf(path, BUFFER_SIZE, "%s/enrollment.ca", folder);
    enrollmentCaCert = readFile(path);

    snprintf(path, BUFFER_SIZE, "%s/enrollment.crt", folder);
    enrollmentClientCert = readFile(path);

    snprintf(path, BUFFER_SIZE, "%s/enrollment.key", folder);
    enrollmentPrivKey = readFile(path);

    enrollmentData.server = server;
    enrollmentData.caCert = enrollmentCaCert;
    enrollmentData.clientCert = enrollmentClientCert;
    enrollmentData.privKey = enrollmentPrivKey;

    return &enrollmentData;
}

static const char* loadPreLoadedRsaKeys(const char* folder) {
    char path[BUFFER_SIZE];
    snprintf(path, BUFFER_SIZE, "%s/pre-loaded-rsa.json", folder);


    if (fs_stat(path, NULL) != 0) {
        printf("Pre-loaded RSA key '%s' not found!\n", path);
        printf("RSA key will be generated by the SDK...\n");
        return NULL;
    }

    char* fileContent = readFile(path);
    if (!fileContent) return NULL;

    size_t bufferSize = strlen(fileContent) + 1;
    char* buffer = malloc(bufferSize);
    strncpy(buffer, fileContent, bufferSize);
    free(fileContent);

    printf("Pre-loaded RSA key '%s' loaded\n", path);
    return buffer;
}

static void sdkHeartbeat() {
    printf("Tributech SDK heartbeat received\n");
}

static void sdkStateChanged(TtState oldState, TtState newState) {
    printf("Tributech SDK state changed from '%s' to '%s'\n", ttStateToString(oldState), ttStateToString(newState));
}

void sendTestDataLoop() {
    TtError err;
    TtStreamId streamInt32 = { 0 };
    if (TT_IS_ERR(ttGetStreamByName("Int32 Stream", &streamInt32))) {
        printf("Could not find int32 stream\n");
    }

    TtStreamId streamInt64 = { 0 };
    if (TT_IS_ERR(ttGetStreamByName("Int64 Stream", &streamInt64))) {
        printf("Could not find int64 stream\n");
    }

    TtStreamId streamFloat = { 0 };
    if (TT_IS_ERR(ttGetStreamByName("Float Stream", &streamFloat))) {
        printf("Could not find float stream\n");
    }

    TtStreamId streamDouble = { 0 };
    if (TT_IS_ERR(ttGetStreamByName("Double Stream", &streamDouble))) {
        printf("Could not find double stream\n");
    }

    TtStreamId streamUtf8 = { 0 };
    if (TT_IS_ERR(ttGetStreamByName("UTF8 Stream", &streamUtf8))) {
        printf("Could not find utf8 stream\n");
    }

    for (uint16_t val = 0;; ++val) {
        if (streamInt32.id[0] != ' ') {
            err = ttAddInt32(&streamInt32, (int32_t)val);
            if (TT_IS_ERR(err)) {
                printf("Could not add value to int32 stream: %s\n", ttErrorToString(err));
            }
        }

        if (streamInt64.id[0] != ' ') {
            err = ttAddInt64(&streamInt64, (int64_t)val);
            if (TT_IS_ERR(err)) {
                printf("Could not add value to int64 stream: %s\n", ttErrorToString(err));
            }
        }

        if (streamFloat.id[0] != ' ') {
            err = ttAddFloat(&streamFloat, (float)val);
            if (TT_IS_ERR(err)) {
                printf("Could not add value to float stream: %s\n", ttErrorToString(err));
            }
        }

        if (streamDouble.id[0] != ' ') {
            err = ttAddDouble(&streamDouble, (double)val);
            if (TT_IS_ERR(err)) {
                printf("Could not add value to double stream: %s\n", ttErrorToString(err));
            }
        }

        if (streamUtf8.id[0] != ' ') {
            char utf8[32];
            snprintf(utf8, sizeof(utf8), "%u - %s", val, ((val & 1) != 0) ? "ð" : "ð");
            err = ttAddUtf8(&streamUtf8, utf8);
            if (TT_IS_ERR(err)) {
                printf("Could not add value to utf8 stream: %s\n", ttErrorToString(err));
            }
        }

        sleep(1);
    }
}

int main(int argc, char* argv[]) {
    signal(SIGPIPE, SIG_IGN);

    if (argc != 4) {
        fprintf(stderr, "Usage: %s <enrollment-folder> <enrollment-server> <mqtt-server>\n", argv[0]);
        return 1;
    }

    const char* enrollmentFolder = argv[1];
    const char* enrollmentServer = argv[2];
    const char* mqttServer = argv[3];

    struct stat st;
    if (stat(enrollmentFolder, &st) != 0 || !S_ISDIR(st.st_mode)) {
        fprintf(stderr, "Enrollment folder '%s' does not exist!", enrollmentFolder);
        return 1;
    }

    if (strchr(enrollmentServer, '/') || !strchr(enrollmentServer, '.')) {
        fprintf(stderr, "Invalid enrollment server '%s'!", enrollmentServer);
        return 1;
    }

    if (strchr(mqttServer, '/') || !strchr(mqttServer, '.')) {
        fprintf(stderr, "Invalid MQTT server '%s'!", mqttServer);
        return 1;
    }

    TtConfig config = {
        .enrollment = loadEnrollmentData(enrollmentFolder, enrollmentServer),
        .heartbeatCallback = sdkHeartbeat,
        .stateCallback = sdkStateChanged,
        .mqttBroker = mqttServer,
        .preLoadedRsaKey = loadPreLoadedRsaKeys(enrollmentFolder),
    };

    TtError err = ttInit(&config);
    if (TT_IS_ERR(err)) {
        printf("Could not initialize the Tributech SDK: %s", ttErrorToString(err));
        return 1;
    }

    sendTestDataLoop();
    return 0;
}
