#include <chrono>
#include <csignal>
#include <cstring>
#include <filesystem>
#include <fstream>
#include <iostream>
#include <sstream>
#include <string>
#include <thread>
#include <vector>

#include <tt_sdk/tt_sdk.h>

static std::string enrollmentCaCert;
static std::string enrollmentClientCert;
static std::string enrollmentPrivKey;
static TtEnrollmentData enrollmentData;

static std::string readFile(const std::filesystem::path& filename)
{
    auto ifs = std::ifstream(filename);
    if (!ifs) {
        std::cerr << "Could not open '" << filename << "'" << std::endl;
        return "";
    }
    std::ostringstream buffer;
    buffer << ifs.rdbuf();
    return buffer.str();
}

static const TtEnrollmentData* loadEnrollmentData(const std::filesystem::path& folder, const std::string& server)
{
    // read file content and store forever
    enrollmentCaCert = readFile(folder / "enrollment.ca");
    enrollmentClientCert = readFile(folder / "enrollment.crt");
    enrollmentPrivKey = readFile(folder / "enrollment.key");

    // store the pointers in the structure
    enrollmentData.server = server.c_str();
    enrollmentData.caCert = enrollmentCaCert.c_str();
    enrollmentData.clientCert = enrollmentClientCert.c_str();
    enrollmentData.privKey = enrollmentPrivKey.c_str();

    // return the loaded enrollment data
    return &enrollmentData;
}

static const char* loadPreLoadedRsaKeys(const std::filesystem::path& folder)
{
    // check if the file exists
    const auto file = folder / "pre-loaded-rsa.json";
    if (!std::filesystem::is_regular_file(file)) {
        std::cout << "Pre-loaded RSA key " << file << " not found!" << std::endl;
        std::cout << "RSA key will be generated by the SDK..." << std::endl;
        return nullptr;
    }

    // load the file
    const auto fileContent = readFile(file);

    // convert into a buffer that is not automatically freed
    const auto bufferSize = fileContent.length() + 1;
    char* buffer = new char[bufferSize];
    snprintf(buffer, bufferSize, "%s", fileContent.c_str());

    // return the loaded data
    std::cout << "Pre-loaded RSA key " << file << " loaded" << std::endl;
    return buffer;
}

static void sdkHeartbeat()
{
    std::cout << "Tributech SDK heartbeat received" << std::endl;
}

static void sdkStateChanged(TtState oldState, TtState newState)
{
    std::cout << "Tributech SDK state changed from '" << ttStateToString(oldState)
              << "' to '" << ttStateToString(newState) << "'" << std::endl;
}

int main(int argc, char* argv[])
{
    // disable signals for broken pipes (sent for broken TCP connections)
    signal(SIGPIPE, SIG_IGN);

    // get the command line options
    if (argc != 4) {
        std::cerr << "Usage: " << argv[0] << " <enrollment-folder> <enrollment-server> <mqtt-server>" << std::endl;
        std::cerr << std::endl;
        std::cerr << "Example: " << argv[0] << " test-data/enrollment/ dev-y.tributech-node.com demeter-mqtt.dev-y.tributech-node.com" << std::endl;
        return 1;
    }
    const std::filesystem::path enrollmentFolder = argv[1];
    const std::string enrollmentServer = argv[2];
    const std::string mqttServer = argv[3];

    // validate the parameters
    if (!std::filesystem::exists(enrollmentFolder)) {
        std::cerr << "Enrollment folder '" << enrollmentFolder.string() << "' does not exist!" << std::endl;
        return 1;
    }
    if (enrollmentServer.find('/') != std::string::npos
        || enrollmentServer.find('.') == std::string::npos) {
        std::cerr << "Invalid enrollment server '" << enrollmentServer << "'!" << std::endl;
        return 1;
    }
    if (mqttServer.find('/') != std::string::npos
        || mqttServer.find('.') == std::string::npos) {
        std::cerr << "Invalid MQTT server '" << mqttServer << "'!" << std::endl;
        return 1;
    }

    // initialize the Tributech SDK
    TtConfig config = {
        .enrollment = loadEnrollmentData(enrollmentFolder, enrollmentServer),
        .heartbeatCallback = &sdkHeartbeat,
        .stateCallback = &sdkStateChanged,
        .mqttBroker = mqttServer.c_str(),
        .preLoadedRsaKey = loadPreLoadedRsaKeys(enrollmentFolder),
    };
    TtError err = ttInit(&config);
    if (TT_IS_ERR(err)) {
        std::cout << "Could not initialize the Tributech SDK: " << ttErrorToString(err) << std::endl;
        return 1;
    }

    // get the device ID
    char deviceId[TT_DEVICE_ID_LEN + 1];
    if (TT_IS_OK(ttGetDeviceId(deviceId, sizeof(deviceId)))) {
        std::cout << "Device ID (agent ID): " << deviceId << std::endl;
    } else {
        std::cout << "Warning: Could not query device ID (agent ID)" << std::endl;
    }

    // get the twin config
    size_t twinConfigLen = 0;
    if (TT_IS_OK(ttGetTwinConfig(nullptr, &twinConfigLen))) {
        std::vector<char> twinConfig;
        twinConfig.resize(twinConfigLen, '\0');
        if (TT_IS_OK(ttGetTwinConfig(twinConfig.data(), &twinConfigLen))) {
            if (twinConfigLen == twinConfig.size()) {
                std::cout << "Loaded " << twinConfigLen << " bytes of twin config (string length is "
                          << strlen(twinConfig.data()) << ")" << std::endl;
            } else {
                std::cout << "Warning: Twin config changed size (from " << twinConfig.size()
                          << " to " << twinConfigLen << ")" << std::endl;
            }
        } else {
            std::cout << "Warning: Could not get twin config" << std::endl;
        }
    } else {
        std::cout << "Warning: Could not get twin config length" << std::endl;
    }

    // get the list of streams
    TtStreamId cur = { 0 };
    err = ttGetNextStream(NULL, &cur);
    if (TT_IS_OK(err)) {
        // run over all streams
        do {
            // get stream details
            TtDataType dataType;
            size_t merkleDepth = 0;
            size_t nameLen = 0;
            err = ttGetStreamDetails(&cur, &dataType, &merkleDepth, &nameLen);
            if (TT_IS_OK(err)) {
                // try to get the stream name
                std::vector<char> nameBuf;
                nameBuf.resize(nameLen + 1, '\0');
                err = ttGetStreamName(&cur, nameBuf.data(), nameBuf.size());
                if (TT_IS_OK(err)) {
                    // make sure we can find the stream by name too
                    TtStreamId byName = { 0 };
                    err = ttGetStreamByName(nameBuf.data(), &byName);
                    if (TT_IS_OK(err)) {
                        // everything looks good
                        std::cout << "Stream '" << cur.id << "':" << std::endl;
                        std::cout << "    Name:         '" << nameBuf.data() << "'" << std::endl;
                        std::cout << "    Type:         " << dataType << std::endl;
                        std::cout << "    Merkle depth: " << merkleDepth << " (" << (1 << merkleDepth) << " values)" << std::endl;
                    } else {
                        std::cout << "Could not get stream by name: " << ttErrorToString(err) << std::endl;
                    }
                } else {
                    std::cout << "Could not get stream name: " << ttErrorToString(err) << std::endl;
                }
            } else {
                std::cout << "Could not get stream details: " << ttErrorToString(err) << std::endl;
            }

            // get the next stream
            err = ttGetNextStream(&cur, &cur);
        } while (TT_IS_OK(err));

        // handle enumeration errors
        if (err != TT_E_NO_MORE) {
            std::cout << "Could not get next stream: " << ttErrorToString(err) << std::endl;
        }
    } else {
        std::cout << "Could not get first stream: " << ttErrorToString(err) << std::endl;
    }

    // get the different streams using their name
    TtStreamId streamInt32 = { 0 };
    if (TT_IS_ERR(ttGetStreamByName("Int32 Stream", &streamInt32))) {
        std::cout << "Could not find int32 stream" << std::endl;
    }
    TtStreamId streamInt64 = { 0 };
    if (TT_IS_ERR(ttGetStreamByName("Int64 Stream", &streamInt64))) {
        std::cout << "Could not find int64 stream" << std::endl;
    }
    TtStreamId streamFloat = { 0 };
    if (TT_IS_ERR(ttGetStreamByName("Float Stream", &streamFloat))) {
        std::cout << "Could not find float stream" << std::endl;
    }
    TtStreamId streamDouble = { 0 };
    if (TT_IS_ERR(ttGetStreamByName("Double Stream", &streamDouble))) {
        std::cout << "Could not find double stream" << std::endl;
    }
    TtStreamId streamUtf8 = { 0 };
    if (TT_IS_ERR(ttGetStreamByName("UTF8 Stream", &streamDouble))) {
        std::cout << "Could not find utf8 stream" << std::endl;
    }

    // send test data in an endless loop
    for (uint16_t val = 0;; ++val) {
        // send data to the different streams
        if (streamInt32.id[0] != '\0') {
            err = ttAddInt32(&streamInt32, (int32_t)val);
            if (TT_IS_ERR(err)) {
                std::cout << "Could not add value to int32 stream: " << ttErrorToString(err) << std::endl;
            }
        } else {
            TT_UNUSED(ttGetStreamByName("Int32 Stream", &streamInt32));
        }
        if (streamInt64.id[0] != '\0') {
            err = ttAddInt64(&streamInt64, (int64_t)val);
            if (TT_IS_ERR(err)) {
                std::cout << "Could not add value to int64 stream: " << ttErrorToString(err) << std::endl;
            }
        } else {
            TT_UNUSED(ttGetStreamByName("Int64 Stream", &streamInt64));
        }
        if (streamFloat.id[0] != '\0') {
            err = ttAddFloat(&streamFloat, (float)val);
            if (TT_IS_ERR(err)) {
                std::cout << "Could not add value to float stream: " << ttErrorToString(err) << std::endl;
            }
        } else {
            TT_UNUSED(ttGetStreamByName("Float Stream", &streamFloat));
        }
        if (streamDouble.id[0] != '\0') {
            err = ttAddDouble(&streamDouble, (double)val);
            if (TT_IS_ERR(err)) {
                std::cout << "Could not add value to double stream: " << ttErrorToString(err) << std::endl;
            }
        } else {
            TT_UNUSED(ttGetStreamByName("Double Stream", &streamDouble));
        }
        if (streamUtf8.id[0] != '\0') {
            char utf8[32];
            snprintf(utf8, sizeof(utf8), "%u - %s", val, ((val & 1) != 0) ? "\U0001f600" : "\U0001F44D");
            err = ttAddUtf8(&streamUtf8, utf8);
            if (TT_IS_ERR(err)) {
                std::cout << "Could not add value to utf8 stream: " << ttErrorToString(err) << std::endl;
            }
        } else {
            TT_UNUSED(ttGetStreamByName("Utf8 Stream", &streamUtf8));
        }

        // we want to send one value per second
        std::this_thread::sleep_for(std::chrono::seconds(1));
    }
}
