/**
 * @file
 *
 * Provides SDK version information.
 * Auto-generated by the build process, DO NOT EDIT!
 */
#ifndef TT_SDK_VERSION_H
#define TT_SDK_VERSION_H

/**
 * @brief The major version number of the SDK.
 */
#define TT_VERSION_MAJOR 1

/**
 * @brief The minor version number of the SDK.
 */
#define TT_VERSION_MINOR 2

/**
 * @brief The patch version number of the SDK.
 */
#define TT_VERSION_PATCH 0

/**
 * @brief The full version string of the SDK.
 */
#define TT_VERSION "1.2.0"

#endif
