/**
 * @file
 *
 * This file hides differences between C and C++ compilers as well as other features
 * that depend on the compiler and programming language version.
 */

#ifndef TT_SDK_CORE_COMPILER_H
#define TT_SDK_CORE_COMPILER_H

// include common header so we have common data type definitions ready
#ifdef __cplusplus
#include <cstddef> // size_t, NULL and others
#include <cstdint> // [u]int[8,16,32]_t, [u]intptr_t and others
#else
#include <stdbool.h> // always available in C++
#include <stddef.h> // size_t and others
#include <stdint.h> // [u]int[8,16,32]_t, [u]intptr_t and others
#endif

/**
 * @brief Helper macro to stringify a token.
 *
 * Do not use this directly, use @ref TT_STRING instead!
 *
 * @param X The token to stringify.
 */
#define TT_STRING2(X) #X

/**
 * @brief Macro to stringify a token.
 *
 * @param X The token to stringify.
 */
#define TT_STRING(X) TT_STRING2(X)

/**
 * @brief A helper macro to get the number of elements in an array.
 *
 * This only works for arrays with fixed length!
 *
 * @param X The name of the fixed-length array.
 */
#define TT_ARRAY_SIZE(X) (sizeof((X)) / sizeof((X)[0]))

/**
 * @brief A helper macro to get the length of a string literal at compile-time.
 *
 * The terminating null is NOT included in the length!
 *
 * @param S The string literal.
 */
#define TT_STR_LEN(S) (TT_ARRAY_SIZE(S) - 1)

/**
 * @brief Define a macro that warns if the caller does not use the return value of a function.
 *
 * This functionality is not well standardized (yet), so we need a few different versions:
 *   - The C++17 (and newer) @c [[nodiscard]] (if available)
 *   - The GCC/clang custom @c __attribute__((__warn_unused_result__)) (if available)
 *
 * If nothing is supported we simply define an empty macro.
 * With an empty macro no checks are performed by the compiler and other tools.
 *
 * The value can be overwritten in the build system with a custom implementation.
 * This can be used for compilers/platforms/tools that use a non-standardized attribute syntax.
 */
#ifndef TT_NO_DISCARD
// no implementation provided by the build environment
#if defined(__cplusplus) && __cplusplus >= 201703L
// we can use C++17 features
#define TT_NO_DISCARD [[nodiscard]]
#else
// no C++17 features, use compiler-specific features if available
#ifdef __GNUC__
// GCC (and clang) support this custom attribute
#define TT_NO_DISCARD __attribute__((__warn_unused_result__))
#else
// we simply define it empty (no checks)
#define TT_NO_DISCARD
#endif
#endif
#endif

/**
 * @brief Define a macro that disables the warnings generated by @ref TT_NO_DISCARD for a single call.
 *
 * This functionality depends on the implementation of @ref TT_NO_DISCARD
 * (which, in turn, depends on the programming language, language version, and compiler):
 *   - The C++17 (and newer) @c [[maybe_unused]] (and @c decltype() as helper)
 *   - The GCC/clang custom @c __attribute__((unused)) (and @c __typeof__() as helper)
 */
#ifndef TT_UNUSED
// no implementation provided by the build environment
#if defined(__cplusplus) && __cplusplus >= 201703L
// we can use C++17 features
#define TT_UNUSED(F)                                   \
    do {                                               \
        [[maybe_unused]] decltype(F) ___tt_unused = F; \
    } while (false)
#else
// no C++17 features, use compiler-specific features if available
#ifdef __GNUC__
// GCC (and clang) support this custom attribute
#define TT_UNUSED(F)                                          \
    do {                                                      \
        __typeof(F) __attribute__((unused)) ___tt_unused = F; \
    } while (false)
#else
// we add nothing to the function call
#define TT_UNUSED(F) F
#endif
#endif
#endif

/**
 * @brief Provides a generic way for compile-time checks.
 *
 * The implementation depends on the language (C vs C++) and language version.
 * There is always a fallback solution, but it does not generate useful error messages.
 *
 * The value can be overwritten in the build system with a custom implementation.
 * This can be used for compilers/platforms/tools that use a non-standardized attribute syntax.
 */
#ifndef TT_STATIC_ASSERT
// no implementation provided by the build environment
#if defined(__cplusplus) && defined(__cpp_static_assert)
// we can use the C++ language feature
#define TT_STATIC_ASSERT(X, M) static_assert((X), M)
#else
#if defined(__STDC_VERSION__) && __STDC_VERSION__ > 201112
// we can use the C feature
#define TT_STATIC_ASSERT(X, M) _Static_assert((X), M)
#else
// nothing available, fall back to a bit of compiler magic
#define TT_STATIC_ASSERT(X, M) typedef char static_assertion_##__LINE__[(!!(X)) * 2 - 1]
#endif
#endif
#endif

/**
 * @brief Provides a generic way to mark a symbol as "public".
 *
 * All symbols are "hidden" due to compiler command line options we set using cmake.
 * Note that the ELF definition of "default visibility" means "public".
 *
 * The value can be overwritten in the build system with a custom implementation.
 * This can be used for compilers/platforms/tools that does not support the extended GCC attribute syntax.
 */
#ifndef TT_PUBLIC
// we assume the GCC extended attribute syntax is available
#define TT_PUBLIC __attribute__((visibility("default")))
#endif

/**
 * @brief Packs a structure.
 *
 * The value can be overwritten in the build system with a custom implementation.
 * This can be used for compilers/platforms/tools that does not support the extended GCC attribute syntax.
 */
#ifndef TT_PACKED
// we assume the GCC extended attribute syntax is available
#define TT_PACKED __attribute__((packed))
#endif

#endif
